
services:

  processamento:
    image: briscese/processamento:latest
    build:
      context: ../processamento
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.12
    depends_on:
      - controller-cadastro-autenticacao
    volumes:
      - ../processamento/src:/app/src

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_postgres=test_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.2

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doxito007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "3050:80"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.3
    depends_on:
      - postgres

  pre-processamento:
    image: briscese/pre-processamento:latest
    build:
      context: ../pre-processamento
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.10
    depends_on:
      - controller-cadastro-autenticacao
    volumes:
      - ../pre-processamento/src:/app/src

  banco-de-dados:
    image: briscese/banco-de-dados:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.11
    depends_on:
      - controller-cadastro-autenticacao
    env_file:
      - .env

  controller-cadastro-autenticacao:
    image: briscese/nc-controller-cadastro-autenticacao:latest
    ports:
      - "3000:3000"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.4
    depends_on:
      - pgadmin
      - postgres

volumes:
  postgres-data:
  front-data:

networks:
  rede_microsservicos:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
